name: GitHub Action to scan the commit for secrets
on: [push]
jobs:
  Execute-secret-check:
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master