name: GitHub Action to scan the commit for secrets
on: [push]
jobs:
  Execute-secret-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: trufflehog-actions-scan
      uses: edplato/trufflehog-actions-scan@master
      with:
        scanArguments: "--regex --entropy=True --max_depth=5 --rules /regexes.json"